/**
 * Centralized icon exports. We re-export from lucide-react so the rest of
 * the app imports from one place — easy to swap libraries later, easy to
 * standardize default size + strokeWidth.
 */
import {
    Phone,
    PhoneCall,
    PhoneOff,
    PhoneIncoming,
    PhoneOutgoing,
    Zap,
    Users,
    ListChecks,
    Clock,
    Settings,
    LogOut,
    Sun,
    Moon,
    Upload,
    Search,
    Trash2,
    BarChart3,
    Activity,
    Ban,
    LayoutGrid,
    Mic,
    MicOff,
    Hash,
    Play,
    Pause,
    Square,
    SkipForward,
    RotateCcw,
    Save,
    ChevronUp,
    ChevronDown,
    X,
    Check,
    AlertTriangle,
    Info,
    Mail,
    MapPin,
    Building2,
    User,
    Tag,
    Truck,
    Smartphone,
    Sparkles,
    Copy,
} from 'lucide-react';

export {
    Phone,
    PhoneCall,
    PhoneOff,
    PhoneIncoming,
    PhoneOutgoing,
    Zap,
    Users,
    ListChecks,
    Clock,
    Settings,
    LogOut,
    Sun,
    Moon,
    Upload,
    Search,
    Trash2,
    BarChart3,
    Activity,
    Ban,
    LayoutGrid,
    Mic,
    MicOff,
    Hash,
    Play,
    Pause,
    Square,
    SkipForward,
    RotateCcw,
    Save,
    ChevronUp,
    ChevronDown,
    X,
    Check,
    AlertTriangle,
    Info,
    Mail,
    MapPin,
    Building2,
    User,
    Tag,
    Truck,
    Smartphone,
    Sparkles,
    Copy,
};

/** Default props the dialer UI uses everywhere — apply via spread. */
export const ICON_DEFAULTS = {
    size: 16,
    strokeWidth: 2,
    'aria-hidden': true,
} as const;
