-- =====================================================================
-- 002 — Phase 3: post-call summaries + suggestion-click telemetry
--
-- call_summaries:  one row per finished call, generated by /api/coach/summarize
-- coach_clicks:    one row per "Suggested replies" chip the agent copies,
--                  for grading prompt quality over time
--
-- Run in Supabase SQL editor or via `supabase db push`.
-- =====================================================================

-- ─── call_summaries ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.call_summaries (
    id              BIGSERIAL PRIMARY KEY,
    call_sid        TEXT NOT NULL UNIQUE,
    summary         TEXT NOT NULL,
    sentiment       TEXT NOT NULL CHECK (sentiment IN ('positive', 'neutral', 'negative', 'mixed')),
    next_action     TEXT,
    key_points      JSONB NOT NULL DEFAULT '[]'::jsonb,
    crm_note        TEXT,
    -- Token spend is useful for cost dashboards later. Nullable for now.
    tokens_in       INTEGER,
    tokens_out      INTEGER,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS call_summaries_call_sid_idx
    ON public.call_summaries (call_sid);

CREATE INDEX IF NOT EXISTS call_summaries_created_at_idx
    ON public.call_summaries (created_at DESC);

-- Realtime so the wrap-up card can subscribe instead of polling.
ALTER PUBLICATION supabase_realtime ADD TABLE public.call_summaries;

ALTER TABLE public.call_summaries ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "authenticated can read summaries" ON public.call_summaries;
CREATE POLICY "authenticated can read summaries"
    ON public.call_summaries
    FOR SELECT
    TO authenticated
    USING (true);

-- (Writes only via service role from /api/coach/summarize.)


-- ─── coach_clicks ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.coach_clicks (
    id              BIGSERIAL PRIMARY KEY,
    call_sid        TEXT NOT NULL,
    suggestion_text TEXT NOT NULL,
    intent          TEXT,
    objection       TEXT,
    suggestion_idx  SMALLINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS coach_clicks_call_sid_idx
    ON public.coach_clicks (call_sid, created_at);

ALTER TABLE public.coach_clicks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "authenticated can read clicks" ON public.coach_clicks;
CREATE POLICY "authenticated can read clicks"
    ON public.coach_clicks
    FOR SELECT
    TO authenticated
    USING (true);

-- (Writes only via service role from /api/coach/click.)
